[package]
name = "one-dim-ca"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.8"
plotters = "0.3.5"
rand = "0.8.5"
rayon = "1.10.0"
